### ISSUE TITLE
Comic "Poorly Drawn Lines" is not loading

### ISSUE THREAD

**Issue by Midrigal** [BBArikL/BDBot#100]
The comic Poorly Drawn Lines is not loading.

The error is: CommandInvokeError: Command 'poorly_drawn_lines' raised an exception: TypeError: object of type 'NoneType' has no len()

**Comment by BBArikL** [comment]
Hi Midrigal and thanks for raising this bug! I think this problem originated in the web manager, probably because of a gocomics site modification... I will try to come up with a fix soon

**Comment by BBArikL** [comment]
I found the problem! I will be pushing the fix soon
