### ISSUE TITLE
New Comic request

### ISSUE THREAD

**Issue by Midrigal** [BBArikL/BDBot#102]
**Is your comic request on GoComics? If yes, please add a link.**
Speed Bump: https://www.gocomics.com/speedbump/2023/06/13
Wallace the Brave: https://www.gocomics.com/wallace-the-brave/2023/06/13
Ripley's Believe It or Not: https://www.gocomics.com/ripleysbelieveitornot/2023/06/13

**Comment by BBArikL** [comment]
Hey this is great picks! I'll definitely add them. Just give until the weekend at least for an update. Thanks for the recommendation :)

**Comment by BBArikL** [comment]
Sorry for the long wait, the comics are now online on the bot! Enjoy ;)
