### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by Kakashi043** [BBArikL/BDBot#11]
I can't pull up Calvin and Hobbes comics in discord.

I type: 
bd!calvin and hobbes random 
bd!calvinandhobbes random
bd!calvin_and_hobbes random

I'm always getting an invalid command error message.
Also bd!the boondocks random does not work but bd!boondocks random does work.
Some of the other comics with multi word names do not work in the command bd!<name of comic> random as well like: 
bd!Hi and Lois random 
bd!Pearls before Swine random

When I use    bd!<name of comic> random  for example bd!calvin and hobbes random 
I expected it would pull up a random calvin and hobbes comic.

Am I putting in the wrong commands?

![Screenshot_20220515-161340](https://user-images.githubusercontent.com/105607003/168492114-4e005403-376e-4b56-bcf5-1cfb94cd5173.png)

**Comment by BBArikL** [comment]
Hello! Fo multi-word comic names, the bot is set up to only accept certain variations of the comic name (putting a space between each of them treats the first word as the command and other words as arguments). For Calvin and Hobbes it only accepts:
`'CalvinandHobbes', 'C&H', 'c&h', 'CH', 'ch'`
You can also find all the aliases by checking out the help command, for exemple Gocomics comics:
`bd!help gocomics`

To improve usability, the bot will change to slash commands and finding you comic will be much more easier during the next update, which should be around June.

**Comment by BBArikL** [comment]
If you have any suggestions on how to improve the usability of the bot, I am open to them and would love external feedback on how it works now. And thank you for using BDBot! :)

**Comment by BBArikL** [comment]
The bot is now only accepting slash commands so getting the comic should be more straightforward. I hope it will provide a better experience now 👍
