### ISSUE TITLE
Heathcliff comic request

### ISSUE THREAD

**Issue by danners430** [BBArikL/BDBot#12]
**Is your comic request on GoComics? If yes, please add a link.**
https://www.gocomics.com/heathcliff

**Comment by BBArikL** [comment]
I like it, I will make sure it gets on the next update of the bot 😄. Thank you for using BDBot!

**Comment by BBArikL** [comment]
I have added Heathcliff as a comic (see https://github.com/BBArikL/BDBot/commit/25390edc1dc71f7f0c4c9732f35fd51ca432be91) and it will be available in one week. The bot will be tested to make sure everything works and then the public bot will be updated with all the new features!
